FROM docker.io/heyste/fedora-sonic-pi-build:20241001 AS sonic-pi

FROM ghcr.io/ublue-os/aurora:40

LABEL org.opencontainers.image.title="iiEdu USB"
LABEL org.opencontainers.image.description="Customized image of Aurora with Sonic Pi"
LABEL org.opencontainers.image.source="https://github.com/heyste/edu-usb"
LABEL org.opencontainers.image.licenses="MIT"

# pull in elixir + erlang
COPY --from=sonic-pi /usr/local/lib/elixir  /usr/local/lib/elixir
COPY --from=sonic-pi /usr/local/lib/erlang  /usr/local/lib/erlang
COPY --from=sonic-pi /usr/local/bin  /usr/local/bin

# pull in ruby gems
COPY --from=sonic-pi /usr/share/gems/ /usr/share/gems

# pull in sonic-pi build
COPY --from=sonic-pi /usr/ii/sonic-pi  /usr/ii/sonic-pi


RUN rpm-ostree install \
        bwm-ng \
        distrobox \
        htop \
        iotop \
        iwd \
        kitty \
        krb5-workstation \
        libvirt-daemon \
        libvirt-daemon-config-network \
        libvirt-daemon-driver-interface \
        libvirt-daemon-driver-network \
        libvirt-daemon-driver-nwfilter \
        libvirt-daemon-driver-qemu \
        libvirt-daemon-driver-secret \
        libvirt-daemon-driver-storage-core \
        libvirt-dbus \
        netcat \
        qemu-kvm \
        sysprof \
        the_silver_searcher \
        vim \
        wireguard-tools \
        zsh \
    && \
    systemctl enable libvirtd.socket \
    && \
    rm -rf /var/lib/unbound/root.key


# Copy custom config to /etc
COPY etc etc

RUN ostree container commit
